# Generated by Django 5.0.7 on 2024-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='candidate',
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
        migrations.DeleteModel(
            name='AcademicFormation',
        ),
        migrations.DeleteModel(
            name='ProfessionalExperience',
        ),
    ]
