# Generated by Django 5.0.7 on 2024-10-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_professionalexperience_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
    ]
